application: personal-web-apps
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: 2.5.2
- name: django
  version: "1.5"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

builtins:
- deferred: on
- remote_api: on

skip_files:
#- ^(/)?static/css/.*
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.less$
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(/)?static/js/dojo/.*

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /css
  static_dir: static/css

# tasks (webapp)
- url: /task/sendmail.*
  script: guestbook.send_mail.app
#  secure: always

- url: .*
  script: main.application
